### PR TITLE
Link to citation instructions in docs

### PR DESCRIPTION
**Pull request by namurphy**
This PR removes the webpage on how to cite PlasmaPy from the website, and instead links to the citation instructions in the stable version of our documentation.  This is to help us avoid having to change the citation instructions in more than one place when we do new releases.

### CODE REVIEW

**Review by StanczakDominik — APPROVED** [review]
Now that's the ratio of removed to added lines I love to see before a review!

**Comment by rocco8773** [comment]
Note, I now have to redo the next YouTube video since this has changed.  I segmented the video so I should only have to redo the section that covers this part.

**Comment by namurphy** [comment]
Ah!  Oops.  I forgot about that part.  On the plus side, maybe people watching the video will get to see your hair grow by half an inch in a fraction of a second?

**Comment by rocco8773** [comment]
Does that mean I can't get a hair cut!? 😳

**Comment by StanczakDominik** [comment]
It feels like this approach won't scale to changes. Can we not simply attach an annotation to the particular time stamp saying, this is how it works now?

**Pull request merged**
