### PR TITLE
Create Search Bar

### PR DESCRIPTION
**Pull request by rocco8773**
This PR places a [Google Custom Search Bar](https://cse.google.com/cse/all) into the top menu.  It also creates a custom landing page for the search results, such that the user is not navigated away form PlasmaPy.

There are still issues to be resolved with the `custom.css`:

- [ ] The search box should not, but does, automatically resizes when text is entered into it.
- [ ] The search box should probably fill up all the remaining space on the right side of the top-menu.
- [ ] There still appears to be a boarder fragment off the top-right of the search box.
- [ ] The cancel **X** in the search box can be made smaller.

### CODE REVIEW

**Comment by rocco8773** [comment]
Will close issue #32 

Should be merged after #35 is merged.

**Comment by StanczakDominik** [comment]
What was wrong with the localsearch plugin version?

**Comment by rocco8773** [comment]
> What was wrong with the localsearch plugin version?

As per my comment on https://github.com/PlasmaPy/plasmapy.github.io/pull/35#issuecomment-593521869, it looked clean but the search was not exhaustive and was creating security warnings.

If those two issues can be fixed, then I have not going back to the `localsearch` plugin.  I just couldn't see how to do that.  The Google Custom Search seemed to be a much better option, except for visuals.  These visuals can be fixed with the CSS though.

**Comment by StanczakDominik** [comment]
Y'know, I managed to completely miss that comment somehow - thanks for pointing it out!

1. I'm pretty sure I've got the security warnings fixed by swapping https://plasmapy.org/ - which produces https-related security warnings for some reason - with https://www.plasmapy.org/ in conf.py. Like I said, I hoped it wouldn't break anything - and I managed to miss that breaking!
2. The about page does not actually contain the word "about", and I'm not sure why https://www.google.com/search?q=about&sitesearch=https%3A%2F%2Fplasmapy.github.io%2F shows "About PlasmaPy" in the title, when the actual page's title seems to be "PlasmaPy"... URL? Cache issue? Either way, that's not a very convincing example :sweat_smile:

**Comment by rocco8773** [comment]
PR #38 was accepted instead

**Pull request closed without merging**
