### PR TITLE
Let Travis CI deploy to GitHub pages

### PR DESCRIPTION
**Pull request by sinoroc**
Travis CI is able to deploy directly to GitHub pages.

GitHub-Issue: #3

### CODE REVIEW

**Comment by sinoroc** [comment]
Change the 'github_token' before merging!
https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token

**Comment by StanczakDominik** [comment]
Awesome, thanks for doing this! I'll get the github token securely encrypted and attached ASAP and merge this.

**Comment by StanczakDominik** [comment]
I'm in a slightly suboptimal setup right now, so I'll merge this and update the key on the live version. Thanks for doing this, @sinoroc !

**Comment by StanczakDominik** [comment]
I think this may have worked. @sinoroc, if you don't mind me asking - did I commit any security atrocities with the github token? :smile:

**Comment by sinoroc** [comment]
Looks like it did work indeed!
I don't see anything wrong security wise regarding the GitHub token.
Glad this helped!

**Comment by StanczakDominik** [comment]
Awesome, thank you so much!

**Comment by sinoroc** [comment]
Aside:
I would advise you to tell GitHub to set `src` as the main branch of this repository. I believe this is the branch one would want to see first when browsing to the source code repository. For example this is where your _README_ lives, so that would be nice to see this first.

**Comment by StanczakDominik** [comment]
Yeah, can't believe we missed that. I'll change that right away.

**Pull request merged**
